config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :students

  root 'departments#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  validates_presence_of :department_name
  validates_uniqueness_of :department_name
  # validates_length_of :department_name, {:maximum => 15}

  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :name, :department_id
  validates_uniqueness_of :name, scope: :department_id

  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :get_department, only: %i[show edit update destroy]

  def index
    @departments = Department.all
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to department_path(@department)
    else
      render 'new'
    end
  end

  def show
    @students = @department.students
  end

  def edit; end

  def update
    if @department.update_attributes(department_params)
      redirect_to department_path(@department)
    else
      render 'edit'
    end
  end

  def destroy
    if @department
      @department.destroy
      redirect_to departments_path
    end
  end

  private

  def get_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:department_name)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :get_student, only: %i[show edit update destroy]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new(department_id: params[:department_id])
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to student_path(@student)
    else
      puts @student.errors.full_messages
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @student.update(student_params)
      redirect_to student_path(@student)
    else
      render 'edit'
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path
  end

  private

  def get_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :department_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/departments/create.html.erb
<h1>Departments#create</h1>
<p>Find me in app/views/departments/create.html.erb</p>

app/views/departments/destroy.html.erb
<h1>Departments#destroy</h1>
<p>Find me in app/views/departments/destroy.html.erb</p>

app/views/departments/edit.html.erb
<h3 class = 'text-center'>Edit Department</h3><br>
<%= form_for @department, validate: true do |f| %>
	<p>
		<strong>Department Name: </strong>
		<%= f.text_field :department_name %>
	</p>
	<br>
	<p>
		<%= f.submit %>
	</p>
<%end%>
<br>
<%= link_to "Back To List", departments_path %>

app/views/departments/index.html.erb
<h1 class = 'text-center'>Departments List</h1><br>
<div class="container-fluid">	
	<div class="col-sm-9"></div>
	<div class="col-sm-3">
		<%= link_to new_department_path, class: "btn btn-success btn-md"  do %> 
			<i class='fa fa-plus'></i>&nbsp; Add Department
		<%end%>
	</div>
</div>
<br>
<br>
<div class = 'container-fluid'>
	<table class='table table-striped table-bordered'>
		<thead>
			<tr class="danger">
				<th>Department Name</th>
				<th class="col-sm-1">View</th>
				<th class="col-sm-1">Edit</th>
				<th class="col-sm-1">Delete</th>
			</tr>
		</thead>
		<tbody>
			<% @departments.each do |dept| %>
				<tr>
					<td><%= dept.department_name %></td>
					<td><%= link_to department_path(dept), class: "btn btn-info btn-sm" do %> 
							<i class='fa fa-eye'></i> 
						<%end%>
					</td>
					<td><%= link_to edit_department_path(dept), class: "btn btn-warning btn-sm" do %>
							<i class='fa fa-pencil'></i>
						<%end%>
					</td>
					<td><%= link_to department_path(dept), method: :delete, :data => {confirm: "Are You Sure?"}, class: "btn btn-danger btn-sm" do %>
							<i class='fa fa-trash'></i>
						<%end%>
					</td>
				</tr>
			<%end%>
		</tbody>
	</table>
</div>
<br>

app/views/departments/new.html.erb
<h3 class = 'text-center'>New Department</h3><br>
<%= form_for @department, validate: true do |f| %>
	<p>
		<strong>Department Name: </strong>
		<%= f.text_field :department_name %>
	</p>
	<br>
	<p>
		<%= f.submit %>
	</p>
<%end%>

<%= link_to "Back To List", departments_path %>

app/views/departments/show.html.erb
<h2 class = "text-center">Welcome To <%= @department.department_name %> Department</h2><br>
<div class="container-fluid">
	<br>
	<div class="col-sm-10">
		<%= link_to departments_path, class: "btn btn-primary btn-md" do %>
			<i class="fa fa-arrow-left">&nbsp; Back To Department List</i>
		<%end%>
	</div>
	<div class="col-sm-2">
		<%= link_to new_student_path(department_id: @department.id), class: "btn btn-success btn-md" do %>
			<i class="fa fa-plus">&nbsp; Add Student</i>
		<%end%>
	</div>
</div>
<br>
<br>
<div class="container-fluid">
	<table class = 'table table-striped table-bordered'>
		<thead>
			<tr class="danger">
				<th>Student Name</th>
				<th class="col-sm-1">View</th>
				<th class="col-sm-1">Edit</th>
				<th class="col-sm-1">Delete</th>
			</tr>
		</thead>
		<tbody>
			<% @students.each do |student| %>
				<tr>
					<td><%= student.name %></td>
					<td><%= link_to student_path(student), class: "btn btn-info btn-sm" do %>
							<i class="fa fa-eye"></i>
						<%end%>
					</td>
					<td><%= link_to edit_student_path(student), class: "btn btn-warning btn-sm" do %>
							<i class="fa fa-pencil"></i>
						<%end%>
					</td>
					<td><%= link_to student_path(student), method: :delete, :data => {confirm: "Are You Sure?"}, class: "btn btn-danger btn-sm" do %>
							<i class="fa fa-trash"></i>
						<%end%>
					</td>
				</tr>
			<%end%>
		</tbody>
	</table>
</div>
<br>

app/views/departments/update.html.erb
<h1>Departments#update</h1>
<p>Find me in app/views/departments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'rails.validations', 'data-turbolinks-track': 'reload' %>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<h3 class = 'text-center'>Edit Student</h3><br>
<%= form_for @student, validate: true do |f| %>
	<p>
		<strong>Student Name: </strong>
		<%= f.text_field :name %>
	</p>
	<p>
		<strong>Department: </strong>
		<%= f.select :department_id, Department.all.map { |d| [d.department_name, d.id]}, include_blank: true %>
	</p>
	<br>
	<p>
		<%= f.submit %>
	</p>
<%end%>

<%= link_to "Back To List", students_path %>

app/views/students/index.html.erb
<h1 class = 'text-center'>Students List</h1><br>
<div class="container-fluid">
	<div class="col-sm-10"></div>
	<div class="col-sm-2">
		<%= link_to new_student_path, class: "btn btn-success btn-md" do %>
			<i class="fa fa-plus"></i>&nbsp; New Student
		<%end%>	
	</div>
</div>
<br>
<br>
<div class="container-fluid">
	<table class = 'table table-striped table-bordered'>
		<thead>
			<tr class="danger">
				<th>Student Name</th>
				<th>Department</th>
				<th class="col-sm-1">View</th>
				<th class="col-sm-1">Edit</th>
				<th class="col-sm-1">Delete</th>
			</tr>
		</thead>
		<tbody>
			<% @students.each do |student| %>
				<tr>
					<td><%= student.name %></td>
					<td><%= student.department.department_name %></td>
					<td><%= link_to student_path(student), class: "btn btn-info btn-sm" do %>
							<i class="fa fa-eye"></i>
						<%end%>
					</td>
					<td><%= link_to edit_student_path(student), class: "btn btn-warning btn-sm" do %>
							<i class="fa fa-pencil"></i>
						<%end%>
					</td>
					<td><%= link_to student_path(student), method: :delete, :data => {confirm: "Are You Sure?"}, class: "btn btn-danger btn-sm" do %>
							<i class="fa fa-trash"></i>
						<%end%>
					</td>
				</tr>
			<%end%>
		</tbody>
	</table>
</div>

app/views/students/new.html.erb
<h3 class = 'text-center'>New Student</h3><br>
<%= form_for @student, validate: true do |f| %>
	<p>
		<strong>Student Name: </strong>
		<%= f.text_field :name %>
	</p>
	<p>
		<strong>Department: </strong>
		<%= f.select :department_id, Department.all.map { |d| [d.department_name, d.id]}, include_blank: true %>
	</p>
	<br>
	<p>
		<%= f.submit %>
	</p>
<%end%>

<%= link_to "Back To List", students_path %>

app/views/students/show.html.erb
<h3 class = "text-center">Student Details</h1>
<p>
	<strong>Student Name: </strong>
	<%= @student.name %>
</p>
<p>
	<strong>Department: </strong>
	<%= @student.department.department_name %>
</p>
<br>
<%= link_to "Edit", edit_student_path(@student) %> &nbsp;&nbsp;
<%= link_to "Back To List", students_path %>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>